import { Data, IProductInput } from '@/types'
import { toSlug } from './utils'

const products: IProductInput[] = [
  // {
  //   name: 'Ardiuno uno with cable',
  //   slug: toSlug('Ardiuno uno with cable'),
  //   category: 'Development-Board',
  //   images: [
  //     '/images/ardiuno-uno-cable-1.webp',
  //     '/images/ardiuno-uno-cable-2.webp',
  //   ],
  //   tags: ['new-arrival'],
  //   isPublished: true,
  //   price: 560,
  //   listPrice: 0,
  //   brand: 'None',
  //   avgRating: 4.71,
  //   numReviews: 7,
  //   ratingDistribution: [
  //     { rating: 1, count: 0 },
  //     { rating: 2, count: 0 },
  //     { rating: 3, count: 0 },
  //     { rating: 4, count: 2 },
  //     { rating: 5, count: 5 },
  //   ],
  //   numSales: 9,
  //   countInStock: 11,
  //   description: 'Dev board',
  //   sizes: [''],
  //   colors: [''],

  //   reviews: [],
  // },
  // {
  //   name: 'Esp32 Camera module',
  //   slug: toSlug('Esp32 Camera module'),
  //   category: 'Development-Board',
  //   images: [
  //     '/images/esp32-cam-1.webp',
  //     '/images/esp32-cam-2.webp',
  //     '/images/esp32-cam-3.webp',
  //   ],
  //   tags: ['featured'],
  //   isPublished: true,
  //   price: 599,
  //   listPrice: 0,
  //   brand: 'AI Thinker',
  //   avgRating: 4.2,
  //   numReviews: 10,
  //   ratingDistribution: [
  //     { rating: 1, count: 1 },
  //     { rating: 2, count: 0 },
  //     { rating: 3, count: 0 },
  //     { rating: 4, count: 4 },
  //     { rating: 5, count: 5 },
  //   ],
  //   numSales: 29,
  //   countInStock: 12,
  //   description: 'Camera module in dev board',

  //   sizes: [''],
  //   colors: [''],

  //   reviews: [],
  // },
  // {
  //   name: 'Luckfox pico',
  //   slug: toSlug('Luckfox pico'),
  //   category: 'Development-Board',
  //   brand: 'Luckfox',
  //   images: [
  //     '/images/luckfox-pico-1.webp',
  //     '/images/luckfox-pico-2.webp',
  //     '/images/luckfox-pico-3.webp',
  //   ],
  //   tags: ['new-arrival'],
  //   isPublished: true,
  //   price: 13.86,
  //   listPrice: 16.03,
  //   avgRating: 4,
  //   numReviews: 12,
  //   ratingDistribution: [
  //     { rating: 1, count: 1 },
  //     { rating: 2, count: 0 },
  //     { rating: 3, count: 2 },
  //     { rating: 4, count: 4 },
  //     { rating: 5, count: 5 },
  //   ],
  //   numSales: 55,
  //   countInStock: 13,
  //   description: 'Development Board',
  //   sizes: ['luckfox-pico-m'],
  //   colors: [''],

  //   reviews: [],
  // },

  //new added
  {
    name: 'Ardiuno uno (smd) with cable',
    slug: toSlug('Ardiuno uno (smd) with cable'),
    category: 'Development-Board',
    images: [
      '/images/ardiuno-uno-smd-cable-1.webp',
      '/images/ardiuno-uno-smd-cable-2.webp',
    ],
    tags: ['new-arrival', 'todays-deal'],
    isPublished: true,
    price: 550,
    listPrice: 495,
    brand: 'Ardiuno',
    avgRating: 0,
    numReviews: 0,
    ratingDistribution: [],
    numSales: 0,
    countInStock: 2,
    description: [
      'Microcontroller ATmega328 (SMD) Interface CH340G',
      'Operating Voltage: 5V. Input Voltage (recommended): 7-12V',
      'Input Voltage (limits): 5-20V',
      'Digital I / O Pins 14 (of which 6 provide PWM output)',
      'Analog Input Pins: 6',
      'DC Current per I Pin: 40 mA',
      'DC Current for 3.3V Pin: 50 mA',
      'Flash Memory: 32 KB (ATmega328) of which 0.5 KB used by bootloader',
      'SRAM: 2 KB (ATmega328)',
      'EEPROM: 1 KB (ATmega328)',
      'Clock Speed: 16 MHz',
    ],
    sizes: ['(smd) with cable'],
    colors: ['Blue'],
    reviews: [],
  },

  {
    name: 'Esp32 Camera module',
    slug: toSlug('Esp32 Camera module'),
    category: 'Development-Board',
    images: [
      '/images/esp32-cam-1.webp',
      '/images/esp32-cam-2.webp',
      '/images/esp32-cam-3.webp',
    ],
    tags: ['new-arrival', 'featured'],
    isPublished: true,
    price: 599,
    listPrice: 0,
    brand: 'AI Thinker',
    avgRating: 0,
    numReviews: 0,
    ratingDistribution: [],
    numSales: 0,
    countInStock: 2,
    description: [
      'Dual-core 32-bit CPU Frequency: 240MHz (main)',
      'Computing Power: 600 DMIPS',
      'SRAM: 520 KB (Built-in)',
      'PSRAM: 4M(external)',
      'Camera Expansion: 16x through-holes with UART,SPI,I2C,PWM,ADC,DAC',
      'Support OV2640 cameras, built-in flash',
      'Support image WiFi upload, TF card and multiple sleep modes',
      'Support STA/AP/STA+AP working mode',
      'Power Supply: 5V via pin header',
    ],
    sizes: ['module with cam'],
    colors: ['Black'],
    reviews: [],
  },
  {
    name: 'Luckfox pico',
    slug: toSlug('Luckfox pico'),
    category: 'Development-Board',
    brand: 'Luckfox',
    images: [
      '/images/luckfox-pico-1.webp',
      '/images/luckfox-pico-2.webp',
      '/images/luckfox-pico-3.webp',
    ],
    tags: ['new-arrival', 'todays-deal'],
    isPublished: true,
    price: 1215,
    listPrice: 1350,
    avgRating: 0,
    numReviews: 0,
    ratingDistribution: [],
    numSales: 0,
    countInStock: 1,
    description: [
      'Processor: Cortex A7 at 1.2GHz + RISC-V',
      'NPU: 0.5TOPS, supports int4, int8 and int16',
      'ISP Input: 4M at 30fps (Max)',
      'Memory: 64 MB DDR2',
      'USB: 2.0 Host/Device',
      'Camera: MIPI CSI 2-lane (Not included)',
      'GPIO: 24x GPIO pins',
      'Default Storage: TF card (Not included)',
      'Pinheader Options',
    ],
    sizes: ['luckfox-pico(soldered)'],
    colors: ['black'],
    reviews: [],
  },

  {
    name: 'Ardiuno NANO Welding Type-C',
    slug: toSlug('Ardiuno NANO Welding Type-C'),
    category: 'Development-Board',
    images: [
      '/images/ardiuno-nano-without-cable-1.webp',
      '/images/ardiuno-nano-without-cable-2.webp',
    ],
    tags: ['new-arrival', 'todays-deal'],
    isPublished: true,
    price: 415,
    listPrice: 490,
    brand: 'Ardiuno',
    avgRating: 0,
    numReviews: 0,
    ratingDistribution: [],
    numSales: 0,
    countInStock: 4,
    description: [
      'CH340G Replace FT232RL',
      '8 analog inputs ports : A0 ~ A7',
      '14 Digital input/output ports : TX, RX,  D2 ~ D13',
      '6 PMW ports : D3, D5, D6, D9, D10, D11',
      '1 pairs of TTL level serial transceiver ports RX/TX',
      'Using Atmega328P-AU MCU',
      'There is bootloader installed in it',
      'Support USB download and Power',
      'Support for external 5V~12V DC power supply',
      'Support power supply by 9V battery',
      'Support ISP download',
    ],
    sizes: ['Type C'],
    colors: ['Without cable'],
    reviews: [],
  },
  {
    name: 'Ardiuno UNO R3 With Cable',
    slug: toSlug('Ardiuno UNO R3 With Cable'),
    category: 'Development-Board',
    images: [
      '/images/arduino-uno-r3-with-cable-1.webp',
      '/images/arduino-uno-r3-with-cable-2.webp',
    ],
    tags: ['new-arrival', 'todays-deal'],
    isPublished: true,
    price: 700,
    listPrice: 825,
    brand: 'Ardiuno',
    avgRating: 0,
    numReviews: 0,
    ratingDistribution: [],
    numSales: 0,
    countInStock: 2,
    description: [
      'Microcontroller: ATmega328',
      'Operating Voltage: 5V',
      'Input Voltage (recommended): 7-12V',
      'Input Voltage (limits): 5-20V',
      'Digital I/O Pins: 14 (of which 6 provide PWM output)',
      'Analog Input Pins: 6',
      'DC Current per I/O Pin: 40 mA',
      'DC Current for 3.3V Pin: 50 mA',
      'Flash Memory: 32 KB (ATmega328) of which 0.5 KB used by bootloader',
      'SRAM: 2 KB (ATmega328)',
      'EEPROM: 1 KB (ATmega328)',
      'Clock Speed: 16 MHz',
    ],
    sizes: ['With cable'],
    colors: ['Blue'],
    reviews: [],
  },

  {
    name: 'ESP32-S3 N16R8',
    slug: toSlug('ESP32-S3 N16R8'),
    category: 'Development-Board',
    images: [
      '/images/esp32-s3 n16r8-1.webp',
      '/images/esp32-s3 n16r8-2.webp',
      '/images/esp32-s3 n16r8-3.webp',
      '/images/esp32-s3 n16r8-4.webp',
      '/images/esp32-s3 n16r8-5.webp',
    ],
    tags: ['new-arrival', 'todays-deal'],
    isPublished: true,
    price: 1125,
    listPrice: 1250,
    brand: 'ESP',
    avgRating: 0,
    numReviews: 0,
    ratingDistribution: [],
    numSales: 0,
    countInStock: 1,
    description: [
      'Equipped with a powerful ESP32-S3 chip',
      'CPU: Dual-core Xtensa LX7, 240 MHz',
      'Flash: 16MB',
      'PSRAM: 8MB',
      'ROM: 384KB',
      'SRAM: 512KB and RTC SRAM: 16KB',
      'WiFi: IEEE 802.11b/g/n, up to 150 Mbps',
      'Bluetooth: Bluetooth 5 LE with speeds up to 2 Mbps',
      'USB-to-Serial: CH340K, max rate 2 Mbps',
      'I/O Interfaces: SPI, UART, I2C, PWM, ADC, DAC',
      'Input Voltage: 5V via USB',
    ],
    sizes: ['With-out cable'],
    colors: ['Black'],
    reviews: [],
  },
  {
    name: 'TP4056 Type-C Micro USB 18650 1A Lithium Battery Charging Board',
    slug: toSlug(
      'TP4056 Type-C Micro USB 18650 1A Lithium Battery Charging Board'
    ),
    category: 'Charging-Module',
    images: [
      '/images/type-c-1a-battery-charging-board-1.webp',
      '/images/type-c-1a-battery-charging-board-2.webp',
    ],
    tags: ['new-arrival'],
    isPublished: true,
    price: 35,
    listPrice: 0,
    brand: 'None',
    avgRating: 0,
    numReviews: 0,
    ratingDistribution: [],
    numSales: 0,
    countInStock: 20,
    description: [
      'Input voltage: DC 5V',
      'Charging cut-off voltage: 4.2V±1%',
      'Maximum charging current: 1000mA',
      'Battery over discharge protection voltage: 2.5V',
      'Battery overcurrent protection current: 3A',
      'The input side has a MICRO USB base, you can directly use the mobile phone charger as the input power to charge the lithium battery',
    ],
    sizes: ['TP4056'],
    colors: ['blue'],
    reviews: [],
  },
  {
    name: 'DC 3V-6V N20 Mini Micro Metal Gear Motor',
    slug: toSlug('DC 3V-6V N20 Mini Micro Metal Gear Motor'),
    category: 'Motor',
    images: [
      '/images/n20_mini_micro_metal_gear_motor_1.webp',
      '/images/n20_mini_micro_metal_gear_motor_2.webp',
      '/images/n20_mini_micro_metal_gear_motor_3.webp',
    ],
    tags: ['new-arrival'],
    isPublished: true,
    price: 200,
    listPrice: 0,
    brand: 'None',
    avgRating: 0,
    numReviews: 0,
    ratingDistribution: [],
    numSales: 0,
    countInStock: 5,
    description: [
      'N20 Gear Motor',
      'Rated voltage: DC 5V',
      'No-load Speed: 60RPM',
      'No-load current: 50mA',
      'Applicable voltage: 3-9V (36-108rpm)',
      'Weight: 20g',
      'Motor Shaft Diameter: 3mm',
      'Motor Shaft Length: 7.2mm',
    ],
    sizes: ['Metal'],
    colors: ['Black'],
    reviews: [],
  },
  {
    name: 'Magnetic Switch',
    slug: toSlug('Magnetic Switch'),
    category: 'Switch',
    images: ['/images/megnetic-switch-1.webp'],
    tags: ['new-arrival'],
    isPublished: true,
    price: 20,
    listPrice: 0,
    brand: 'None',
    avgRating: 0,
    numReviews: 0,
    ratingDistribution: [],
    numSales: 0,
    countInStock: 10,
    description: [
      'Glass Length 14mm',
      'Glass Diameter 2mm',
      'Max. Switching Voltage 300VDC',
      'Min.Breakdown Voltage 150VDC',
      'Max. Contact Rating 10W',
      'Max. Switching Current 0.55A',
      'Max. Operate time 0.45ms',
      'Bounce time 0.25ms',
      'Max. Release time 0.35ms',
      'Resonant Frequency 5000HZ',
      'Max. Operating 400HZ',
    ],
    sizes: ['2x14mm'],
    colors: ['transparent'],
    reviews: [],
  },
  {
    name: 'Slide Switch 3pin',
    slug: toSlug('Sldie Switch 3pin'),
    category: 'Switch',
    images: ['/images/silde-switch-3pin.webp'],
    tags: ['new-arrival'],
    isPublished: true,
    price: 10,
    listPrice: 0,
    brand: 'None',
    avgRating: 0,
    numReviews: 0,
    ratingDistribution: [],
    numSales: 0,
    countInStock: 20,
    description: ['On-Off Mini Slide Switch 3pin', '2 Position'],
    sizes: ['4mm'],
    colors: ['slide'],
    reviews: [],
  },
  {
    name: 'Lasers Dot Diode Module(650nm 6mm 5V 5 million watt)',
    slug: toSlug('Lasers Dot Diode Module(650nm 6mm 5V 5 million watt)'),
    category: 'Diode',
    images: ['/images/lasers-dot-diode-1.webp'],
    tags: ['new-arrival'],
    isPublished: true,
    price: 35,
    listPrice: 35,
    brand: 'None',
    avgRating: 0,
    numReviews: 0,
    ratingDistribution: [],
    numSales: 0,
    countInStock: 10,
    description: [
      'Laser wavelength: 650nm (Red)',
      'Copper Head Diameter is 6mm',
      'Light power: <5mW',
      'Supply Voltage: 5VDC',
      'Operating Current: <40mA',
      'Power lead length: 75mm',
    ],
    sizes: ['5v'],
    colors: ['Red'],
    reviews: [],
  },
  {
    name: 'MQ-2 Detection Smoke Module',
    slug: toSlug('MQ-2 Detection Smoke Module'),
    category: 'Sensor-Module',
    images: ['/images/mq-2_detection_smoke_module-1.webp'],
    tags: ['new-arrival'],
    isPublished: true,
    price: 140,
    listPrice: 140,
    brand: 'None',
    avgRating: 0,
    numReviews: 0,
    ratingDistribution: [],
    numSales: 0,
    countInStock: 5,
    description: [
      'Operating voltage: DC 5V',
      'Analog Output (AO): 0~5V analog output voltage',
      'Digital Output (DO): 0V or 5V output',
      'Configuration: Through Potentiometer (adjusts the output level transition)',
      'Preheat Duration: 20s',
    ],
    sizes: ['MQ-2'],
    colors: ['Blue'],
    reviews: [],
  },
  {
    name: 'MQ-4 Detection Smoke Module',
    slug: toSlug('MQ-4 Detection Smoke Module'),
    category: 'Sensor-Module',
    images: ['/images/mq-4_detection_smoke_module-1.webp'],
    tags: ['new-arrival'],
    isPublished: true,
    price: 150,
    listPrice: 150,
    brand: 'None',
    avgRating: 0,
    numReviews: 0,
    ratingDistribution: [],
    numSales: 0,
    countInStock: 5,
    description: [
      'Operating voltage: DC 3v-5V',
      'Detecting Range: 300ppm to 10000ppm',
      'Analog Output (AO): 0~5V analog output voltage',
      'Digital Output (DO): 0V or 5V output',
      'Configuration: Through Potentiometer (adjusts the output level transition)',
    ],
    sizes: ['MQ-4'],
    colors: ['Blue'],
    reviews: [],
  },
  // {
  //   name: 'Decrum Mens Plain Long Sleeve T-Shirt - Comfortable Soft Fashion V Neck Full Sleeves Jersey Shirts',
  //   slug: toSlug(
  //     'Decrum Mens Plain Long Sleeve T-Shirt - Comfortable Soft Fashion V Neck Full Sleeves Jersey Shirts'
  //   ),
  //   category: 'T-Shirts',
  //   brand: 'Jerzees',
  //   images: ['/images/p14-1.jpg', '/images/p14-2.jpg'],
  //   tags: ['todays-deal'],
  //   isPublished: true,
  //   price: 26.95,
  //   listPrice: 46.03,
  //   avgRating: 3.85,
  //   numReviews: 14,
  //   ratingDistribution: [
  //     { rating: 1, count: 0 },
  //     { rating: 2, count: 2 },
  //     { rating: 3, count: 3 },
  //     { rating: 4, count: 4 },
  //     { rating: 5, count: 5 },
  //   ],
  //   numSales: 54,
  //   countInStock: 14,
  //   description:
  //     'Elevate your outfit with this soft long sleeve t shirt men. This full sleeves tee is the ultimate upgrade from your regular cotton t-shirt. ',
  //   sizes: ['XL', 'XXL'],
  //   colors: ['Yellow', 'White'],

  //   reviews: [],
  // },
  // {
  //   name: "Muscle Cmdr Men's Slim Fit Henley Shirt Long&Short Business Sleeve Casual 3 Metal Buton Placket Casual Stylish T-Shirt",
  //   slug: toSlug(
  //     "Muscle Cmdr Men's Slim Fit Henley Shirt Long&Short Business Sleeve Casual 3 Metal Buton Placket Casual Stylish T-Shirt"
  //   ),
  //   category: 'T-Shirts',
  //   brand: ' Muscle Cmdr',
  //   images: ['/images/p15-1.jpg', '/images/p15-2.jpg'],
  //   tags: ['new-arrival', 'featured'],
  //   isPublished: true,
  //   price: 29.99,
  //   listPrice: 35.99,
  //   avgRating: 3.66,
  //   numReviews: 15,
  //   ratingDistribution: [
  //     { rating: 1, count: 1 },
  //     { rating: 2, count: 2 },
  //     { rating: 3, count: 3 },
  //     { rating: 4, count: 4 },
  //     { rating: 5, count: 5 },
  //   ],
  //   numSales: 54,
  //   countInStock: 15,
  //   description:
  //     "Slim Fit Design:Men's Muscle Slim Fit Button Henley Shirts are designed to fit snugly against your body, accentuating your muscles and creating a sleek silhouette that's perfect for any occasion. ",
  //   sizes: ['XL', 'XXL'],
  //   colors: ['Green', 'Yellow'],

  //   reviews: [],
  // },
  // {
  //   name: 'Hanes Mens Long Sleeve Beefy Henley Shirt',
  //   slug: toSlug('Hanes Mens Long Sleeve Beefy Henley Shirt'),
  //   category: 'T-Shirts',
  //   brand: 'Jerzees',
  //   images: ['/images/p16-1.jpg', '/images/p16-2.jpg'],
  //   tags: ['best-seller', 'todays-deal'],
  //   isPublished: true,
  //   price: 25.3,
  //   listPrice: 32.99,
  //   avgRating: 3.46,
  //   numReviews: 13,
  //   ratingDistribution: [
  //     { rating: 1, count: 1 },
  //     { rating: 2, count: 2 },
  //     { rating: 3, count: 3 },
  //     { rating: 4, count: 4 },
  //     { rating: 5, count: 3 },
  //   ],
  //   countInStock: 16,
  //   numSales: 56,
  //   description:
  //     'Heavyweight cotton (Heathers are 60% cotton/40% polyester; Pebblestone is 75% cotton/25% polyester)',
  //   sizes: ['XL', 'XXL'],
  //   colors: ['Grey', 'White'],

  //   reviews: [],
  // },
  // // Jeans
  // {
  //   name: 'Silver Jeans Co. Mens Jace Slim Fit Bootcut Jeans',
  //   slug: toSlug('Silver Jeans Co. Mens Jace Slim Fit Bootcut Jeans'),
  //   category: 'Jeans',
  //   brand: 'Silver Jeans Co',
  //   images: ['/images/p21-1.jpg', '/images/p21-2.jpg'],
  //   tags: ['new-arrival'],
  //   isPublished: true,
  //   price: 95.34,
  //   listPrice: 0,
  //   avgRating: 4.71,
  //   numReviews: 7,
  //   ratingDistribution: [
  //     { rating: 1, count: 0 },
  //     { rating: 2, count: 0 },
  //     { rating: 3, count: 0 },
  //     { rating: 4, count: 2 },
  //     { rating: 5, count: 5 },
  //   ],
  //   countInStock: 54,
  //   numSales: 21,
  //   description:
  //     'Silver Jeans Co. Jace Slim Fit Bootcut Jeans - Consider Jace a modern cowboy jean. It sits below the waist and features a slim fit through the hip and thigh. Finished with an 18” bootcut leg opening that complements the slimmer silhouette while still fitting over boots',
  //   sizes: ['30Wx30L', '34Wx30L', '36Wx30L'],
  //   colors: ['Blue', 'Grey'],

  //   reviews: [],
  // },
  // {
  //   name: "Levi's mens 505 Regular Fit Jeans (Also Available in Big & Tall)",
  //   slug: toSlug(
  //     "Levi's mens 505 Regular Fit Jeans (Also Available in Big & Tall)"
  //   ),
  //   category: 'Jeans',
  //   brand: "Levi's",
  //   images: ['/images/p22-1.jpg', '/images/p22-2.jpg'],
  //   tags: ['featured'],
  //   isPublished: true,
  //   price: 59.99,
  //   listPrice: 69.99,
  //   avgRating: 4.2,
  //   numReviews: 10,
  //   ratingDistribution: [
  //     { rating: 1, count: 1 },
  //     { rating: 2, count: 0 },
  //     { rating: 3, count: 0 },
  //     { rating: 4, count: 4 },
  //     { rating: 5, count: 5 },
  //   ],
  //   countInStock: 22,
  //   numSales: 54,
  //   description:
  //     'A veritable classic, this 505 is made to have a comfortable look and style.',
  //   sizes: ['30Wx30L', '34Wx30L', '36Wx30L'],
  //   colors: ['Blue', 'Grey'],

  //   reviews: [],
  // },
  // {
  //   name: 'Essentials Mens Straight-Fit Stretch Jean',
  //   slug: toSlug('Essentials Mens Straight-Fit Stretch Jean'),
  //   category: 'Jeans',
  //   brand: 'Essentials',
  //   images: ['/images/p23-1.jpg', '/images/p23-2.jpg'],
  //   tags: ['best-seller'],
  //   isPublished: true,
  //   price: 38.9,
  //   listPrice: 45,
  //   avgRating: 4,
  //   numReviews: 12,
  //   ratingDistribution: [
  //     { rating: 1, count: 1 },
  //     { rating: 2, count: 0 },
  //     { rating: 3, count: 2 },
  //     { rating: 4, count: 4 },
  //     { rating: 5, count: 5 },
  //   ],
  //   countInStock: 23,
  //   numSales: 54,
  //   description:
  //     'These classic 5-pocket straight-fit jeans are crafted with a bit of stretch for additional comfort and to help maintain their shape',
  //   sizes: ['30Wx30L', '34Wx30L', '36Wx30L'],
  //   colors: ['Grey', 'Blue'],

  //   reviews: [],
  // },
  // {
  //   name: "Buffalo David Bitton Mens Men's Driven Relaxed Denim JeansJeans",
  //   slug: toSlug(
  //     "Buffalo David Bitton Mens Men's Driven Relaxed Denim JeansJeans"
  //   ),
  //   category: 'Jeans',
  //   brand: 'Buffalo David Bitton',
  //   images: ['/images/p24-1.jpg', '/images/p24-2.jpg'],
  //   tags: ['todays-deal'],
  //   isPublished: true,
  //   price: 69.99,
  //   listPrice: 100,
  //   avgRating: 3.85,
  //   numReviews: 14,
  //   ratingDistribution: [
  //     { rating: 1, count: 0 },
  //     { rating: 2, count: 2 },
  //     { rating: 3, count: 3 },
  //     { rating: 4, count: 4 },
  //     { rating: 5, count: 5 },
  //   ],
  //   countInStock: 24,
  //   numSales: 53,
  //   description:
  //     'Stretch recycled denim jeans in an authentic and sanded wash blue. Features a comfortable low-rise waist with a relaxed fit at the leg. The distressed look gives these jeans an effortlessly worn-in feel. The eco-friendly logo patch in tan and red is at the back waistband. The signature maple leaf graphic is debossed at the zip-fly.',
  //   sizes: ['30Wx30L', '34Wx30L', '36Wx30L'],
  //   colors: ['Blue', 'Grey'],

  //   reviews: [],
  // },
  // {
  //   name: 'Dickies Mens Relaxed Fit Carpenter Jean',
  //   slug: toSlug('Dickies Mens Relaxed Fit Carpenter Jean'),
  //   category: 'Jeans',
  //   brand: 'Dickies',
  //   images: ['/images/p25-1.jpg', '/images/p25-2.jpg'],
  //   tags: ['new-arrival', 'featured'],
  //   isPublished: true,
  //   price: 95.34,
  //   listPrice: 0,
  //   avgRating: 3.66,
  //   numReviews: 15,
  //   ratingDistribution: [
  //     { rating: 1, count: 1 },
  //     { rating: 2, count: 2 },
  //     { rating: 3, count: 3 },
  //     { rating: 4, count: 4 },
  //     { rating: 5, count: 5 },
  //   ],
  //   countInStock: 25,
  //   numSales: 48,
  //   description:
  //     'Relaxed work jean with traditional carpenter-style pockets and logo patch at back pockets',
  //   sizes: ['30Wx30L', '34Wx30L', '36Wx30L'],
  //   colors: ['Blue', 'Grey'],

  //   reviews: [],
  // },
  // {
  //   name: 'Wrangler mens Premium Performance Cowboy Cut Slim Fit Jean',
  //   slug: toSlug('Wrangler mens Premium Performance Cowboy Cut Slim Fit Jean'),
  //   category: 'Jeans',
  //   brand: 'Wrangler',
  //   images: ['/images/p26-1.jpg', '/images/p26-2.jpg'],
  //   tags: ['best-seller', 'todays-deal'],
  //   isPublished: true,
  //   price: 81.78,
  //   listPrice: 149.99,
  //   avgRating: 3.46,
  //   numReviews: 13,
  //   ratingDistribution: [
  //     { rating: 1, count: 1 },
  //     { rating: 2, count: 2 },
  //     { rating: 3, count: 3 },
  //     { rating: 4, count: 4 },
  //     { rating: 5, count: 3 },
  //   ],
  //   countInStock: 26,
  //   numSales: 48,
  //   description:
  //     'Designed with a functional fit in mind, these jeans are made to stack over your favorite pair of boots. Constructed with a slim fit in the waist, seat, and thigh, this jean is made for both function and comfort for long days in the saddle.',
  //   sizes: ['30Wx30L', '34Wx30L', '36Wx30L'],
  //   colors: ['Blue', 'Grey'],

  //   reviews: [],
  // },
  // // Watches
  // {
  //   name: "Seiko Men's Analogue Watch with Black Dial",
  //   slug: toSlug("Seiko Men's Analogue Watch with Black Dial"),
  //   category: 'Wrist Watches',
  //   brand: 'Seiko',
  //   images: ['/images/p31-1.jpg', '/images/p31-2.jpg'],
  //   tags: ['new-arrival'],
  //   isPublished: true,
  //   price: 530.0,
  //   listPrice: 0,
  //   avgRating: 4.71,
  //   numReviews: 7,
  //   ratingDistribution: [
  //     { rating: 1, count: 0 },
  //     { rating: 2, count: 0 },
  //     { rating: 3, count: 0 },
  //     { rating: 4, count: 2 },
  //     { rating: 5, count: 5 },
  //   ],
  //   countInStock: 31,
  //   numSales: 48,
  //   description:
  //     'Casing: Case made of stainless steel Case shape: round Case colour: silver Glass: Hardlex Clasp type: Fold over clasp with safety',
  //   sizes: [],
  //   colors: [],

  //   reviews: [],
  // },
  // {
  //   name: 'SEIKO 5 Sport SRPJ83 Beige Dial Nylon Automatic Watch, Beige, Automatic Watch',
  //   slug: toSlug(
  //     'SEIKO 5 Sport SRPJ83 Beige Dial Nylon Automatic Watch, Beige, Automatic Watch'
  //   ),
  //   category: 'Wrist Watches',
  //   brand: 'Seiko',
  //   images: ['/images/p32-1.jpg', '/images/p32-2.jpg'],
  //   tags: ['featured'],
  //   isPublished: true,
  //   price: 375.83,
  //   listPrice: 400,
  //   avgRating: 4.2,
  //   numReviews: 10,
  //   ratingDistribution: [
  //     { rating: 1, count: 1 },
  //     { rating: 2, count: 0 },
  //     { rating: 3, count: 0 },
  //     { rating: 4, count: 4 },
  //     { rating: 5, count: 5 },
  //   ],
  //   countInStock: 32,
  //   numSales: 48,
  //   description:
  //     'Seiko 5 Sports Collection Inspired by vintage field/aviator style: Automatic with manual winding capability',
  //   sizes: [],
  //   colors: [],

  //   reviews: [],
  // },
  // {
  //   name: "Casio Men's Heavy Duty Analog Quartz Stainless Steel Strap, Silver, 42 Casual Watch ",
  //   slug: toSlug(
  //     "Casio Men's Heavy Duty Analog Quartz Stainless Steel Strap, Silver, 42 Casual Watch"
  //   ),
  //   category: 'Wrist Watches',
  //   brand: 'Casio',
  //   images: ['/images/p33-1.jpg', '/images/p33-2.jpg'],
  //   tags: ['best-seller'],
  //   isPublished: true,
  //   price: 60.78,
  //   listPrice: 0,
  //   avgRating: 4,
  //   numReviews: 12,
  //   ratingDistribution: [
  //     { rating: 1, count: 1 },
  //     { rating: 2, count: 0 },
  //     { rating: 3, count: 2 },
  //     { rating: 4, count: 4 },
  //     { rating: 5, count: 5 },
  //   ],
  //   countInStock: 33,
  //   numSales: 48,
  //   description:
  //     'The Casio range is growing with this model  MWA-100H-1AVEF. Sporting a stainless steel case with a brushed finish, it will easily withstand all the shocks of everyday life.',
  //   sizes: [],
  //   colors: [],

  //   reviews: [],
  // },
  // {
  //   name: 'Casio Classic Silver-Tone Stainless Steel Band Date Indicator Watch',
  //   slug: toSlug(
  //     'Casio Classic Silver-Tone Stainless Steel Band Date Indicator Watch'
  //   ),
  //   category: 'Wrist Watches',
  //   brand: 'Casio',
  //   images: ['/images/p34-1.jpg', '/images/p34-2.jpg'],
  //   tags: ['todays-deal'],
  //   isPublished: true,
  //   price: 34.22,
  //   listPrice: 54.99,
  //   avgRating: 3.85,
  //   numReviews: 14,
  //   ratingDistribution: [
  //     { rating: 1, count: 0 },
  //     { rating: 2, count: 2 },
  //     { rating: 3, count: 3 },
  //     { rating: 4, count: 4 },
  //     { rating: 5, count: 5 },
  //   ],
  //   countInStock: 34,
  //   numSales: 48,
  //   description:
  //     'The new MTPVD01D-7EV is a classic 50 meter water resistant stainless steel watch now updated with a white dial. This elegant 3 hand, date display timepiece is perfect for any setting.',
  //   sizes: [],
  //   colors: [],

  //   reviews: [],
  // },
  // {
  //   name: "Fossil Men's Grant Stainless Steel Quartz Chronograph Watch",
  //   slug: toSlug("Fossil Men's Grant Stainless Steel Quartz Chronograph Watch"),
  //   category: 'Wrist Watches',
  //   brand: 'Fossil',
  //   images: ['/images/p35-1.jpg', '/images/p35-2.jpg'],
  //   tags: ['new-arrival', 'featured'],
  //   isPublished: true,
  //   price: 171.22,
  //   listPrice: 225,
  //   avgRating: 3.66,
  //   numReviews: 15,
  //   ratingDistribution: [
  //     { rating: 1, count: 1 },
  //     { rating: 2, count: 2 },
  //     { rating: 3, count: 3 },
  //     { rating: 4, count: 4 },
  //     { rating: 5, count: 5 },
  //   ],
  //   countInStock: 35,
  //   numSales: 48,
  //   description:
  //     'Chronograph watch featuring silver- and blue-tone case, blue sunray dial, and silver-tone Roman numeral indices',
  //   sizes: [],
  //   colors: ['Blue', 'Black', 'Sliver'],

  //   reviews: [],
  // },
  // {
  //   name: "Fossil Men's Machine Stainless Steel Quartz Watch",
  //   slug: toSlug("Fossil Men's Machine Stainless Steel Quartz Watch"),
  //   category: 'Wrist Watches',
  //   brand: 'Fossil',
  //   images: ['/images/p36-1.jpg', '/images/p36-2.jpg'],
  //   tags: ['best-seller', 'todays-deal'],
  //   isPublished: true,
  //   price: 158.21,
  //   listPrice: 229.0,
  //   avgRating: 3.46,
  //   numReviews: 13,
  //   ratingDistribution: [
  //     { rating: 1, count: 1 },
  //     { rating: 2, count: 2 },
  //     { rating: 3, count: 3 },
  //     { rating: 4, count: 4 },
  //     { rating: 5, count: 3 },
  //   ],
  //   countInStock: 36,
  //   numSales: 49,
  //   description:
  //     'In masculine black-on-black, our industrial-inspired Machine watch will add a fresh, modern touch to your casual look. This Machine watch also features a three hand movement on a stainless steel bracelet.',
  //   sizes: [],
  //   colors: ['Brown', 'Sliver', 'Black'],

  //   reviews: [],
  // },
  // // Sneakers
  // {
  //   name: 'adidas Mens Grand Court 2.0 Training Shoes Training Shoes',
  //   slug: toSlug('adidas Mens Grand Court 2.0 Training Shoes Training Shoes'),
  //   category: 'Shoes',
  //   brand: 'adidas',
  //   images: ['/images/p41-1.jpg', '/images/p41-2.jpg'],
  //   tags: ['new-arrival'],
  //   isPublished: true,
  //   price: 81.99,
  //   listPrice: 0,
  //   avgRating: 4.71,
  //   numReviews: 7,
  //   ratingDistribution: [
  //     { rating: 1, count: 0 },
  //     { rating: 2, count: 0 },
  //     { rating: 3, count: 0 },
  //     { rating: 4, count: 2 },
  //     { rating: 5, count: 5 },
  //   ],
  //   countInStock: 41,
  //   numSales: 48,
  //   description:
  //     'Cloudfoam Comfort sockliner is ultra-soft and plush, with two layers of cushioning topped with soft, breathable mesh',
  //   sizes: ['8', '9', '10'],
  //   colors: ['White', 'Black', 'Grey'],

  //   reviews: [],
  // },
  // {
  //   name: "ziitop Men's Running Walking Shoes Fashion Sneakers Mesh Dress Shoes Business Oxfords Shoes Lightweight Casual Breathable Work Formal Shoes",
  //   slug: toSlug(
  //     "ziitop Men's Running Walking Shoes Fashion Sneakers Mesh Dress Shoes Business Oxfords Shoes Lightweight Casual Breathable Work Formal Shoes"
  //   ),
  //   category: 'Shoes',
  //   brand: 'ziitop',
  //   images: ['/images/p42-1.jpg', '/images/p42-2.jpg'],
  //   tags: ['featured'],
  //   isPublished: true,
  //   price: 39.97,
  //   listPrice: 49.96,
  //   avgRating: 4.2,
  //   numReviews: 10,
  //   ratingDistribution: [
  //     { rating: 1, count: 1 },
  //     { rating: 2, count: 0 },
  //     { rating: 3, count: 0 },
  //     { rating: 4, count: 4 },
  //     { rating: 5, count: 5 },
  //   ],
  //   countInStock: 42,
  //   numSales: 50,
  //   description:
  //     'Cloudfoam Comfort sockliner is ultra-soft and plush, with two layers of cushioning topped with soft, breathable mesh',
  //   sizes: ['8', '9', '10'],
  //   colors: ['Beige', 'Black', 'Grey'],

  //   reviews: [],
  // },
  // {
  //   name: 'Skechers mens Summits High Range Hands Free Slip-in Shoes Work shoe',
  //   slug: toSlug(
  //     'Skechers mens Summits High Range Hands Free Slip-in Shoes Work shoe'
  //   ),
  //   category: 'Shoes',
  //   brand: 'Skechers',
  //   images: ['/images/p43-1.jpg', '/images/p43-2.jpg'],
  //   tags: ['best-seller'],
  //   isPublished: true,
  //   price: 99.99,
  //   listPrice: 0,
  //   avgRating: 4,
  //   numReviews: 12,
  //   ratingDistribution: [
  //     { rating: 1, count: 1 },
  //     { rating: 2, count: 0 },
  //     { rating: 3, count: 2 },
  //     { rating: 4, count: 4 },
  //     { rating: 5, count: 5 },
  //   ],
  //   countInStock: 43,
  //   numSales: 72,
  //   description:
  //     'Step into easy-wearing comfort with Skechers Hands Free Slip-ins™: Summits - High Range. Along with our Exclusive Heel Pillow™ holds your foot securely in place, this vegan style features a unique pop-up Skechers Slip-ins™ molded heel panel, a mesh upper with fixed laces',
  //   sizes: ['8', '9', '10'],
  //   colors: ['Navy', 'Black', 'Grey'],

  //   reviews: [],
  // },
  // {
  //   name: 'DLWKIPV Mens Running Shoes Tennis Cross Training Sneakers Fashion Non Slip Outdoor Walking Jogging Shoes Mesh Light Flexible Comfortable Breathable Shoes',
  //   slug: toSlug(
  //     'DLWKIPV Mens Running Shoes Tennis Cross Training Sneakers Fashion Non Slip Outdoor Walking Jogging Shoes Mesh Light Flexible Comfortable Breathable Shoes'
  //   ),
  //   category: 'Shoes',
  //   brand: 'DLWKIPV',
  //   images: ['/images/p44-1.jpg', '/images/p44-2.jpg'],
  //   tags: ['todays-deal'],
  //   isPublished: true,
  //   price: 36.99,
  //   listPrice: 56.9,
  //   avgRating: 3.85,
  //   numReviews: 14,
  //   ratingDistribution: [
  //     { rating: 1, count: 0 },
  //     { rating: 2, count: 2 },
  //     { rating: 3, count: 3 },
  //     { rating: 4, count: 4 },
  //     { rating: 5, count: 5 },
  //   ],
  //   countInStock: 44,
  //   numSales: 72,
  //   description:
  //     'Design: Mesh vamp, ventilation. Sole anti-slip groove design, shock absorption and anti-slip. The inside of the shoe is wide and soft, bringing you a good comfortable experience',
  //   sizes: ['8', '9', '10', '11', '12'],
  //   colors: ['Brown', 'Black', 'Grey'],

  //   reviews: [],
  // },
  // {
  //   name: "ASICS Men's GT-2000 13 Running Shoes",
  //   slug: toSlug("ASICS Men's GT-2000 13 Running Shoes"),
  //   category: 'Shoes',
  //   brand: 'ASICS',
  //   images: ['/images/p45-1.jpg', '/images/p45-2.jpg'],
  //   tags: ['new-arrival', 'featured'],
  //   isPublished: true,
  //   price: 179.95,
  //   listPrice: 200,
  //   avgRating: 3.66,
  //   numReviews: 15,
  //   ratingDistribution: [
  //     { rating: 1, count: 1 },
  //     { rating: 2, count: 2 },
  //     { rating: 3, count: 3 },
  //     { rating: 4, count: 4 },
  //     { rating: 5, count: 5 },
  //   ],
  //   countInStock: 45,
  //   numSales: 64,
  //   description:
  //     "At least 50% of the shoe's main upper material is made with recycled content to reduce waste and carbon emissions",
  //   sizes: ['8', '9', '10', '11'],
  //   colors: ['Blue', 'Black', 'Grey'],

  //   reviews: [],
  // },
  // {
  //   name: "Mens Wearbreeze Shoes, Urban - Ultra Comfortable Shoes, Breeze Shoes for Men, Men's Mesh Dress Sneakers Business Shoes",
  //   slug: toSlug(
  //     "Mens Wearbreeze Shoes, Urban - Ultra Comfortable Shoes, Breeze Shoes for Men, Men's Mesh Dress Sneakers Business Shoes"
  //   ),
  //   category: 'Shoes',
  //   brand: 'Generic',
  //   images: ['/images/p46-1.jpg', '/images/p46-2.jpg'],
  //   tags: ['best-seller', 'todays-deal'],
  //   isPublished: true,
  //   price: 32.99,
  //   listPrice: 80,
  //   avgRating: 3.46,
  //   numReviews: 13,
  //   ratingDistribution: [
  //     { rating: 1, count: 1 },
  //     { rating: 2, count: 2 },
  //     { rating: 3, count: 3 },
  //     { rating: 4, count: 4 },
  //     { rating: 5, count: 3 },
  //   ],
  //   countInStock: 46,
  //   numSales: 48,
  //   description:
  //     'Cloudfoam Comfort sockliner is ultra-soft and plush, with two layers of cushioning topped with soft, breathable mesh',
  //   sizes: ['8', '9', '10', '11'],
  //   colors: ['Green', 'Black', 'Grey'],

  //   reviews: [],
  // },
]

const data: Data = {
  products,
  headerMenus: [
    {
      name: "Today's Deal",
      href: '/search?tag=todays-deal',
    },
    {
      name: 'New Arrivals',
      href: '/search?tag=new-arrival',
    },
    {
      name: 'Featured Products',
      href: '/search?tag=featured',
    },
    {
      name: 'Best Sellers',
      href: '/search?tag=best-seller',
    },
    {
      name: 'Browsing History',
      href: '/#browsing-history',
    },
    {
      name: 'Customer Service',
      href: '/page/customer-service',
    },
    {
      name: 'About Us',
      href: '/page/about-us',
    },
    {
      name: 'Help',
      href: '/page/help',
    },
  ],
  carousels: [
    {
      title: 'Most Popular ESP32 Camera For Sale',
      buttonCaption: 'Shop Now',
      image: '/images/Banner_ESP32-CAM.webp',
      url: '/search?category=Modeule',
      isPublished: true,
    },
    {
      title: 'Most Popular Luckfox pico For Sale',
      buttonCaption: 'Shop Now',
      image: '/images/Luckfox-Pico-M.webp',
      url: '/search?category=Development-Board',
      isPublished: true,
    },
    {
      title: 'Most Popular Arduino For Sale',
      buttonCaption: 'See More',
      image: '/images/Arduino_Banner.webp',
      url: '/search?category=Develipment-Board',
      isPublished: true,
    },
  ],
}
export default data
