import { Data, IProductInput, IUserInput } from '@/types'
import { toSlug } from './utils'
import bcrypt from 'bcryptjs'

const products: IProductInput[] = [
  //new added
  {
    name: 'Ardiuno uno (smd) with cable',
    slug: toSlug('Ardiuno uno (smd) with cable'),
    category: 'Development-Board',
    images: [
      '/images/ardiuno-uno-smd-cable-1.webp',
      '/images/ardiuno-uno-smd-cable-2.webp',
    ],
    tags: ['new-arrival', 'todays-deal'],
    isPublished: true,
    price: 495,
    listPrice: 550,
    brand: 'Ardiuno',
    avgRating: 0,
    numReviews: 0,
    ratingDistribution: [],
    numSales: 0,
    countInStock: 2,
    description: [
      'Microcontroller ATmega328 (SMD) Interface CH340G',
      'Operating Voltage: 5V. Input Voltage (recommended): 7-12V',
      'Input Voltage (limits): 5-20V',
      'Digital I / O Pins 14 (of which 6 provide PWM output)',
      'Analog Input Pins: 6',
      'DC Current per I Pin: 40 mA',
      'DC Current for 3.3V Pin: 50 mA',
      'Flash Memory: 32 KB (ATmega328) of which 0.5 KB used by bootloader',
      'SRAM: 2 KB (ATmega328)',
      'EEPROM: 1 KB (ATmega328)',
      'Clock Speed: 16 MHz',
    ],
    sizes: ['(smd) with cable'],
    colors: ['Blue'],
    reviews: [],
  },

  {
    name: 'Esp32 Camera module',
    slug: toSlug('Esp32 Camera module'),
    category: 'Development-Board',
    images: [
      '/images/esp32-cam-1.webp',
      '/images/esp32-cam-2.webp',
      '/images/esp32-cam-3.webp',
    ],
    tags: ['new-arrival', 'featured', 'todays-deal'],
    isPublished: true,
    price: 720,
    listPrice: 850,
    brand: 'AI Thinker',
    avgRating: 0,
    numReviews: 0,
    ratingDistribution: [],
    numSales: 0,
    countInStock: 2,
    description: [
      'Dual-core 32-bit CPU Frequency: 240MHz (main)',
      'Computing Power: 600 DMIPS',
      'SRAM: 520 KB (Built-in)',
      'PSRAM: 4M(external)',
      'Camera Expansion: 16x through-holes with UART,SPI,I2C,PWM,ADC,DAC',
      'Support OV2640 cameras, built-in flash',
      'Support image WiFi upload, TF card and multiple sleep modes',
      'Support STA/AP/STA+AP working mode',
      'Power Supply: 5V via pin header',
    ],
    sizes: ['module with cam'],
    colors: ['Black'],
    reviews: [],
  },
  {
    name: 'Luckfox pico',
    slug: toSlug('Luckfox pico'),
    category: 'Development-Board',
    brand: 'Luckfox',
    images: [
      '/images/luckfox-pico-1.webp',
      '/images/luckfox-pico-2.webp',
      '/images/luckfox-pico-3.webp',
    ],
    tags: ['new-arrival', 'todays-deal'],
    isPublished: true,
    price: 1215,
    listPrice: 1350,
    avgRating: 0,
    numReviews: 0,
    ratingDistribution: [],
    numSales: 0,
    countInStock: 1,
    description: [
      'Processor: Cortex A7 at 1.2GHz + RISC-V',
      'NPU: 0.5TOPS, supports int4, int8 and int16',
      'ISP Input: 4M at 30fps (Max)',
      'Memory: 64 MB DDR2',
      'USB: 2.0 Host/Device',
      'Camera: MIPI CSI 2-lane (Not included)',
      'GPIO: 24x GPIO pins',
      'Default Storage: TF card (Not included)',
      'Pinheader Options',
    ],
    sizes: ['luckfox-pico(soldered)'],
    colors: ['black'],
    reviews: [],
  },

  {
    name: 'Ardiuno NANO Welding Type-C',
    slug: toSlug('Ardiuno NANO Welding Type-C'),
    category: 'Development-Board',
    images: [
      '/images/ardiuno-nano-without-cable-1.webp',
      '/images/ardiuno-nano-without-cable-2.webp',
    ],
    tags: ['new-arrival', 'todays-deal'],
    isPublished: true,
    price: 415,
    listPrice: 490,
    brand: 'Ardiuno',
    avgRating: 0,
    numReviews: 0,
    ratingDistribution: [],
    numSales: 0,
    countInStock: 4,
    description: [
      'CH340G Replace FT232RL',
      '8 analog inputs ports : A0 ~ A7',
      '14 Digital input/output ports : TX, RX,  D2 ~ D13',
      '6 PMW ports : D3, D5, D6, D9, D10, D11',
      '1 pairs of TTL level serial transceiver ports RX/TX',
      'Using Atmega328P-AU MCU',
      'There is bootloader installed in it',
      'Support USB download and Power',
      'Support for external 5V~12V DC power supply',
      'Support power supply by 9V battery',
      'Support ISP download',
    ],
    sizes: ['Type C'],
    colors: ['Without cable'],
    reviews: [],
  },
  {
    name: 'Ardiuno UNO R3 With Cable',
    slug: toSlug('Ardiuno UNO R3 With Cable'),
    category: 'Development-Board',
    images: [
      '/images/arduino-uno-r3-with-cable-1.webp',
      '/images/arduino-uno-r3-with-cable-2.webp',
    ],
    tags: ['new-arrival', 'todays-deal'],
    isPublished: true,
    price: 700,
    listPrice: 825,
    brand: 'Ardiuno',
    avgRating: 0,
    numReviews: 0,
    ratingDistribution: [],
    numSales: 0,
    countInStock: 2,
    description: [
      'Microcontroller: ATmega328',
      'Operating Voltage: 5V',
      'Input Voltage (recommended): 7-12V',
      'Input Voltage (limits): 5-20V',
      'Digital I/O Pins: 14 (of which 6 provide PWM output)',
      'Analog Input Pins: 6',
      'DC Current per I/O Pin: 40 mA',
      'DC Current for 3.3V Pin: 50 mA',
      'Flash Memory: 32 KB (ATmega328) of which 0.5 KB used by bootloader',
      'SRAM: 2 KB (ATmega328)',
      'EEPROM: 1 KB (ATmega328)',
      'Clock Speed: 16 MHz',
    ],
    sizes: ['With cable'],
    colors: ['Blue'],
    reviews: [],
  },

  {
    name: 'ESP32-S3 N16R8',
    slug: toSlug('ESP32-S3 N16R8'),
    category: 'Development-Board',
    images: [
      '/images/esp32-s3 n16r8-1.webp',
      '/images/esp32-s3 n16r8-2.webp',
      '/images/esp32-s3 n16r8-3.webp',
      '/images/esp32-s3 n16r8-4.webp',
      '/images/esp32-s3 n16r8-5.webp',
    ],
    tags: ['new-arrival', 'todays-deal'],
    isPublished: true,
    price: 710,
    listPrice: 790,
    brand: 'ESP',
    avgRating: 0,
    numReviews: 0,
    ratingDistribution: [],
    numSales: 0,
    countInStock: 1,
    description: [
      'Equipped with a powerful ESP32-S3 chip',
      'CPU: Dual-core Xtensa LX7, 240 MHz',
      'Flash: 16MB',
      'PSRAM: 8MB',
      'ROM: 384KB',
      'SRAM: 512KB and RTC SRAM: 16KB',
      'WiFi: IEEE 802.11b/g/n, up to 150 Mbps',
      'Bluetooth: Bluetooth 5 LE with speeds up to 2 Mbps',
      'USB-to-Serial: CH340K, max rate 2 Mbps',
      'I/O Interfaces: SPI, UART, I2C, PWM, ADC, DAC',
      'Input Voltage: 5V via USB',
    ],
    sizes: ['With-out cable'],
    colors: ['Black'],
    reviews: [],
  },
  {
    name: 'TP4056 Type-C Micro USB 18650 1A Lithium Battery Charging Board',
    slug: toSlug(
      'TP4056 Type-C Micro USB 18650 1A Lithium Battery Charging Board'
    ),
    category: 'Charging-Module',
    images: [
      '/images/type-c-1a-battery-charging-board-1.webp',
      '/images/type-c-1a-battery-charging-board-2.webp',
    ],
    tags: ['new-arrival'],
    isPublished: true,
    price: 35,
    listPrice: 0,
    brand: 'None',
    avgRating: 0,
    numReviews: 0,
    ratingDistribution: [],
    numSales: 0,
    countInStock: 20,
    description: [
      'Input voltage: DC 5V',
      'Charging cut-off voltage: 4.2V±1%',
      'Maximum charging current: 1000mA',
      'Battery over discharge protection voltage: 2.5V',
      'Battery overcurrent protection current: 3A',
      'The input side has a MICRO USB base, you can directly use the mobile phone charger as the input power to charge the lithium battery',
    ],
    sizes: ['TP4056'],
    colors: ['blue'],
    reviews: [],
  },
  {
    name: 'DC 3V-6V N20 Mini Micro Metal Gear Motor',
    slug: toSlug('DC 3V-6V N20 Mini Micro Metal Gear Motor'),
    category: 'Motor',
    images: [
      '/images/n20_mini_micro_metal_gear_motor_1.webp',
      '/images/n20_mini_micro_metal_gear_motor_2.webp',
      '/images/n20_mini_micro_metal_gear_motor_3.webp',
    ],
    tags: ['new-arrival'],
    isPublished: true,
    price: 200,
    listPrice: 0,
    brand: 'None',
    avgRating: 0,
    numReviews: 0,
    ratingDistribution: [],
    numSales: 0,
    countInStock: 5,
    description: [
      'N20 Gear Motor',
      'Rated voltage: DC 5V',
      'No-load Speed: 60RPM',
      'No-load current: 50mA',
      'Applicable voltage: 3-9V (36-108rpm)',
      'Weight: 20g',
      'Motor Shaft Diameter: 3mm',
      'Motor Shaft Length: 7.2mm',
    ],
    sizes: ['Metal'],
    colors: ['Black'],
    reviews: [],
  },
  {
    name: 'Magnetic Switch',
    slug: toSlug('Magnetic Switch'),
    category: 'Switch',
    images: ['/images/megnetic-switch-1.webp'],
    tags: ['new-arrival'],
    isPublished: true,
    price: 20,
    listPrice: 0,
    brand: 'None',
    avgRating: 0,
    numReviews: 0,
    ratingDistribution: [],
    numSales: 0,
    countInStock: 10,
    description: [
      'Glass Length 14mm',
      'Glass Diameter 2mm',
      'Max. Switching Voltage 300VDC',
      'Min.Breakdown Voltage 150VDC',
      'Max. Contact Rating 10W',
      'Max. Switching Current 0.55A',
      'Max. Operate time 0.45ms',
      'Bounce time 0.25ms',
      'Max. Release time 0.35ms',
      'Resonant Frequency 5000HZ',
      'Max. Operating 400HZ',
    ],
    sizes: ['2x14mm'],
    colors: ['transparent'],
    reviews: [],
  },
  {
    name: 'Slide Switch 3pin',
    slug: toSlug('Sldie Switch 3pin'),
    category: 'Switch',
    images: ['/images/silde-switch-3pin.webp'],
    tags: ['new-arrival'],
    isPublished: true,
    price: 10,
    listPrice: 0,
    brand: 'None',
    avgRating: 0,
    numReviews: 0,
    ratingDistribution: [],
    numSales: 0,
    countInStock: 20,
    description: ['On-Off Mini Slide Switch 3pin', '2 Position'],
    sizes: ['4mm'],
    colors: ['slide'],
    reviews: [],
  },
  {
    name: 'Lasers Dot Diode Module(650nm 6mm 5V 5 million watt)',
    slug: toSlug('Lasers Dot Diode Module(650nm 6mm 5V 5 million watt)'),
    category: 'Diode',
    images: ['/images/lasers-dot-diode-1.webp'],
    tags: ['new-arrival'],
    isPublished: true,
    price: 35,
    listPrice: 0,
    brand: 'None',
    avgRating: 0,
    numReviews: 0,
    ratingDistribution: [],
    numSales: 0,
    countInStock: 10,
    description: [
      'Laser wavelength: 650nm (Red)',
      'Copper Head Diameter is 6mm',
      'Light power: <5mW',
      'Supply Voltage: 5VDC',
      'Operating Current: <40mA',
      'Power lead length: 75mm',
    ],
    sizes: ['5v'],
    colors: ['Red'],
    reviews: [],
  },
  {
    name: 'MQ-2 Detection Smoke Module',
    slug: toSlug('MQ-2 Detection Smoke Module'),
    category: 'Sensor-Module',
    images: ['/images/mq-2_detection_smoke_module-1.webp'],
    tags: ['new-arrival'],
    isPublished: true,
    price: 140,
    listPrice: 0,
    brand: 'None',
    avgRating: 0,
    numReviews: 0,
    ratingDistribution: [],
    numSales: 0,
    countInStock: 5,
    description: [
      'Operating voltage: DC 5V',
      'Analog Output (AO): 0~5V analog output voltage',
      'Digital Output (DO): 0V or 5V output',
      'Configuration: Through Potentiometer (adjusts the output level transition)',
      'Preheat Duration: 20s',
    ],
    sizes: ['MQ-2'],
    colors: ['Blue'],
    reviews: [],
  },
  {
    name: 'MQ-4 Detection Smoke Module',
    slug: toSlug('MQ-4 Detection Smoke Module'),
    category: 'Sensor-Module',
    images: ['/images/mq-4_detection_smoke_module-1.webp'],
    tags: ['new-arrival'],
    isPublished: true,
    price: 150,
    listPrice: 0,
    brand: 'None',
    avgRating: 0,
    numReviews: 0,
    ratingDistribution: [],
    numSales: 0,
    countInStock: 5,
    description: [
      'Operating voltage: DC 3v-5V',
      'Detecting Range: 300ppm to 10000ppm',
      'Analog Output (AO): 0~5V analog output voltage',
      'Digital Output (DO): 0V or 5V output',
      'Configuration: Through Potentiometer (adjusts the output level transition)',
    ],
    sizes: ['MQ-4'],
    colors: ['Blue'],
    reviews: [],
  },
]

const users: IUserInput[] = [
  {
    name: 'Admin',
    email: 'admin@example.com',
    password: bcrypt.hashSync('123456', 5),
    role: 'Admin',
    address: {
      fullName: 'Admin Admin',
      street: '121',
      city: 'Dhaka',
      division: 'Dhaka',
      postalCode: '1001',
      phone: '123-456-7890',
    },
    paymentMethod: 'Bikash',
    emailVerified: false,
  },
  {
    name: 'Tester',
    email: 'tester@example.com',
    password: bcrypt.hashSync('123456', 5),
    role: 'User',
    address: {
      fullName: 'Tester Tester',
      street: '123',
      city: 'Dhaka',
      division: 'Dhaka',
      postalCode: '1002',
      phone: '123-456-7890',
    },
    paymentMethod: 'Cash On Delivery',
    emailVerified: false,
  },
]

const data: Data = {
  users,
  products,
  headerMenus: [
    {
      name: "Today's Deal",
      href: '/search?tag=todays-deal',
    },
    {
      name: 'New Arrivals',
      href: '/search?tag=new-arrival',
    },
    {
      name: 'Featured Products',
      href: '/search?tag=featured',
    },
    {
      name: 'Best Sellers',
      href: '/search?tag=best-seller',
    },
    {
      name: 'Browsing History',
      href: '/#browsing-history',
    },
    {
      name: 'Customer Service',
      href: '/page/customer-service',
    },
    {
      name: 'About Us',
      href: '/page/about-us',
    },
    {
      name: 'Help',
      href: '/page/help',
    },
  ],
  carousels: [
    {
      title: 'Most Popular ESP32 Camera For Sale',
      buttonCaption: 'Shop Now',
      image: '/images/Banner_ESP32-CAM.webp',
      url: '/search?category=Development-Board',
      isPublished: true,
    },
    {
      title: 'Most Popular Luckfox pico For Sale',
      buttonCaption: 'Shop Now',
      image: '/images/Luckfox-Pico-M.webp',
      url: '/search?category=Development-Board',
      isPublished: true,
    },
    {
      title: 'Most Popular Arduino For Sale',
      buttonCaption: 'See More',
      image: '/images/Arduino_Banner.webp',
      url: '/search?category=Development-Board',
      isPublished: true,
    },
  ],
}
export default data
